# Generated by Django 4.2.7 on 2023-11-05 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('bloodgroup', models.CharField(choices=[('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve')], max_length=5)),
                ('profession', models.CharField(max_length=100)),
                ('tshirt_size', models.CharField(choices=[('S', 'S - Small'), ('M', 'M - Medium'), ('L', 'L - Large'), ('XL', 'XL - Extra Large'), ('XXL', 'XXL - Extra Extra Large'), ('XXXL', 'XXXL - Extra Extra Extra Large')], max_length=5)),
                ('spouse_check', models.BooleanField(default=False)),
                ('child_checkbox', models.BooleanField(default=False)),
                ('number_of_children', models.IntegerField(blank=True, default=0, null=True)),
                ('payment_method', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('handcash', 'Hand Cash')], max_length=10)),
                ('hand_cash_to', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('total_member', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Registration')),
                ('unique_id', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
    ]
